export {default as Home} from './Home/Home'
export {default as Browse} from './Browse/Browse'
export {default as Details} from './Details/Details'
export {default as Profile} from './Profile/Profile'
export {default as Streams} from './Streams/Streams'